// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaRegistroAlumnos.Data;

#nullable disable

namespace SistemaRegistroAlumnos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251026215002_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.Alumno", b =>
                {
                    b.Property<int>("Id_Alumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Alumno"));

                    b.Property<string>("Apm_Alumno")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("App_Alumno")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Calle_Alum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Cod_Programa")
                        .HasColumnType("int");

                    b.Property<string>("Colonia_Alum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Fecha_Nac")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gen_Alumno")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Id_Carrera_Alum")
                        .HasColumnType("int");

                    b.Property<int>("Id_Semestre_Alum")
                        .HasColumnType("int");

                    b.Property<int>("Id_Status_Alum")
                        .HasColumnType("int");

                    b.Property<string>("Nom_Alumno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Num_Casa")
                        .HasColumnType("int");

                    b.Property<string>("Num_Control")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("Num_Ext")
                        .HasColumnType("int");

                    b.HasKey("Id_Alumno");

                    b.HasIndex("Id_Carrera_Alum");

                    b.HasIndex("Id_Semestre_Alum");

                    b.HasIndex("Id_Status_Alum");

                    b.HasIndex("Num_Control")
                        .IsUnique();

                    b.HasIndex("Nom_Alumno", "App_Alumno");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.Asistencia", b =>
                {
                    b.Property<int>("Id_Asistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Asistencia"));

                    b.Property<DateTime>("Fecha_Asia")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Alumno_Asia")
                        .HasColumnType("int");

                    b.Property<int>("Id_EstadoAsistencia_Asia")
                        .HasColumnType("int");

                    b.Property<int>("Id_Unidad_Asia")
                        .HasColumnType("int");

                    b.HasKey("Id_Asistencia");

                    b.HasIndex("Fecha_Asia");

                    b.HasIndex("Id_Alumno_Asia");

                    b.HasIndex("Id_EstadoAsistencia_Asia");

                    b.HasIndex("Id_Unidad_Asia");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.Calificacion", b =>
                {
                    b.Property<int>("Id_Calificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Calificacion"));

                    b.Property<decimal>("Calif_Final")
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Alumno_Calif")
                        .HasColumnType("int");

                    b.Property<int>("Id_Unidad_Calif")
                        .HasColumnType("int");

                    b.HasKey("Id_Calificacion");

                    b.HasIndex("Id_Alumno_Calif");

                    b.HasIndex("Id_Unidad_Calif");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.Carrera", b =>
                {
                    b.Property<int>("Id_Carrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Carrera"));

                    b.Property<string>("Cod_Carrera")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Creditos_Carrera")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Carrera")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id_Carrera");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.EstadoAsistencia", b =>
                {
                    b.Property<int>("Id_EstadoAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_EstadoAsistencia"));

                    b.Property<string>("Estado_Asistencia")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Razon_Inasistencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_EstadoAsistencia");

                    b.ToTable("EstadosAsistencia");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.Materia", b =>
                {
                    b.Property<int>("Id_Materia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Materia"));

                    b.Property<string>("Clave_Materia")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Creditos_Materia")
                        .HasColumnType("int");

                    b.Property<int>("Id_Carrera_Materia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Materia")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id_Materia");

                    b.HasIndex("Id_Carrera_Materia");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.PerfilSocioeconomico", b =>
                {
                    b.Property<int>("Id_Perfil_SE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Perfil_SE"));

                    b.Property<int>("Id_Alumno")
                        .HasColumnType("int");

                    b.Property<decimal?>("Ingreso_Familiar")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Personas_Hogar")
                        .HasColumnType("int");

                    b.Property<string>("Vivienda_Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Perfil_SE");

                    b.HasIndex("Id_Alumno")
                        .IsUnique();

                    b.ToTable("PerfilesSocioeconomicos");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.Semestre", b =>
                {
                    b.Property<int>("Id_Semestre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Semestre"));

                    b.Property<DateTime>("Fecha_Final")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Num_Semestre")
                        .HasColumnType("int");

                    b.HasKey("Id_Semestre");

                    b.ToTable("Semestres");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.StatusAlumno", b =>
                {
                    b.Property<int>("Id_Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Status"));

                    b.Property<string>("Estado_Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Razon_Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Status");

                    b.ToTable("StatusAlumnos");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.Unidad", b =>
                {
                    b.Property<int>("Id_Unidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Unidad"));

                    b.Property<int>("Creditos_Unidad")
                        .HasColumnType("int");

                    b.Property<int>("Horas_Clase")
                        .HasColumnType("int");

                    b.Property<int>("Id_Materia_Unidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Unidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Unidad");

                    b.HasIndex("Id_Materia_Unidad");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.Alumno", b =>
                {
                    b.HasOne("SistemaRegistroAlumnos.Models.Carrera", "Carrera")
                        .WithMany("Alumnos")
                        .HasForeignKey("Id_Carrera_Alum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRegistroAlumnos.Models.Semestre", "Semestre")
                        .WithMany("Alumnos")
                        .HasForeignKey("Id_Semestre_Alum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRegistroAlumnos.Models.StatusAlumno", "StatusAlumno")
                        .WithMany("Alumnos")
                        .HasForeignKey("Id_Status_Alum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Semestre");

                    b.Navigation("StatusAlumno");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.Asistencia", b =>
                {
                    b.HasOne("SistemaRegistroAlumnos.Models.Alumno", "Alumno")
                        .WithMany("Asistencias")
                        .HasForeignKey("Id_Alumno_Asia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRegistroAlumnos.Models.EstadoAsistencia", "EstadoAsistencia")
                        .WithMany("Asistencias")
                        .HasForeignKey("Id_EstadoAsistencia_Asia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRegistroAlumnos.Models.Unidad", "Unidad")
                        .WithMany("Asistencias")
                        .HasForeignKey("Id_Unidad_Asia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("EstadoAsistencia");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.Calificacion", b =>
                {
                    b.HasOne("SistemaRegistroAlumnos.Models.Alumno", "Alumno")
                        .WithMany("Calificaciones")
                        .HasForeignKey("Id_Alumno_Calif")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRegistroAlumnos.Models.Unidad", "Unidad")
                        .WithMany("Calificaciones")
                        .HasForeignKey("Id_Unidad_Calif")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.Materia", b =>
                {
                    b.HasOne("SistemaRegistroAlumnos.Models.Carrera", "Carrera")
                        .WithMany("Materias")
                        .HasForeignKey("Id_Carrera_Materia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.PerfilSocioeconomico", b =>
                {
                    b.HasOne("SistemaRegistroAlumnos.Models.Alumno", "Alumno")
                        .WithOne("PerfilSocioeconomico")
                        .HasForeignKey("SistemaRegistroAlumnos.Models.PerfilSocioeconomico", "Id_Alumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.Unidad", b =>
                {
                    b.HasOne("SistemaRegistroAlumnos.Models.Materia", "Materia")
                        .WithMany("Unidades")
                        .HasForeignKey("Id_Materia_Unidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.Alumno", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Calificaciones");

                    b.Navigation("PerfilSocioeconomico")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.Carrera", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Materias");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.EstadoAsistencia", b =>
                {
                    b.Navigation("Asistencias");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.Materia", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.Semestre", b =>
                {
                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.StatusAlumno", b =>
                {
                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("SistemaRegistroAlumnos.Models.Unidad", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Calificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
